// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using projeto_escritorio.Data;

#nullable disable

namespace projeto_escritorio.Migrations;

[DbContext(typeof(ClienteContext))]
partial class ClienteContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "6.0.10")
            .HasAnnotation("Relational:MaxIdentifierLength", 64);

        modelBuilder.Entity("projeto_escritorio.Models.Cliente", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                b.Property<string>("Cpf")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.Property<string>("Endereco")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.Property<string>("Nome")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.Property<string>("Telefone")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.HasKey("Id");

                b.ToTable("Clientes");
            });
#pragma warning restore 612, 618
    }
}
